"""change type of some fields

Revision ID: f2a3ac28c74e
Revises: 5086ccb16840
Create Date: 2024-07-11 20:10:55.101862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2a3ac28c74e'
down_revision: Union[str, None] = '5086ccb16840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'image',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'image',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=False)
    # ### end Alembic commands ###
